// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: department_migrate.sql

package repository

import (
	"context"
)

const countActiveApprovalsByDepartment = `-- name: CountActiveApprovalsByDepartment :one
SELECT count(*) FROM department_product_approvals
WHERE department_id = ? AND revoked_at IS NULL
`

// CountActiveApprovalsByDepartment feeds the migration preview: how
// many active approvals would be copied to the successor.
func (q *Queries) CountActiveApprovalsByDepartment(ctx context.Context, departmentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveApprovalsByDepartment, departmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConflictingLicenses = `-- name: CountConflictingLicenses :one
SELECT count(*) FROM licenses
WHERE licenses.owning_department_id = ?1
  AND EXISTS (
    SELECT 1 FROM licenses l2
    WHERE l2.product_id = licenses.product_id
      AND l2.owning_department_id = ?2
      AND l2.license_slug = licenses.license_slug
  )
`

type CountConflictingLicensesParams struct {
	FromDepartmentID int64
	ToDepartmentID   int64
}

// CountConflictingLicenses counts the source-department licenses that
// MigrateLicensesToDepartment skips because the destination already
// has a row with the same (product_id, license_slug); moving them
// would violate UNIQUE(product_id, owning_department_id,
// license_slug). Used for the preview estimate and, inside the same
// transaction after the UPDATE, for the skip report (moved rows no
// longer match, so the count is stable across the UPDATE). Every
// outer column reference is fully qualified as licenses.* because
// sqlc reports unqualified ones as ambiguous once the l2 subquery
// is in scope (same workaround as prior queries).
func (q *Queries) CountConflictingLicenses(ctx context.Context, arg CountConflictingLicensesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConflictingLicenses, arg.FromDepartmentID, arg.ToDepartmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLicensesByDepartment = `-- name: CountLicensesByDepartment :one
SELECT count(*) FROM licenses
WHERE owning_department_id = ?
`

// CountLicensesByDepartment feeds the migration preview: how many
// licenses the retired department still owns.
func (q *Queries) CountLicensesByDepartment(ctx context.Context, owningDepartmentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLicensesByDepartment, owningDepartmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActiveApprovalsForMigration = `-- name: ListActiveApprovalsForMigration :many
SELECT id, department_id, product_id, status, scope_type, conditions, approved_by_app_user_id, approved_at, expires_at, revoked_at, revoked_by_app_user_id, revoke_reason, approval_source, source_request_id, note, created_at, updated_at FROM department_product_approvals
WHERE department_id = ? AND revoked_at IS NULL
ORDER BY product_id
`

// ListActiveApprovalsForMigration returns every active approval of
// the retired department with all columns, so the handler can copy
// each row to the successor via CreateApproval (skipping products the
// successor already has an active approval for).
func (q *Queries) ListActiveApprovalsForMigration(ctx context.Context, departmentID int64) ([]DepartmentProductApproval, error) {
	rows, err := q.db.QueryContext(ctx, listActiveApprovalsForMigration, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepartmentProductApproval
	for rows.Next() {
		var i DepartmentProductApproval
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.ProductID,
			&i.Status,
			&i.ScopeType,
			&i.Conditions,
			&i.ApprovedByAppUserID,
			&i.ApprovedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedByAppUserID,
			&i.RevokeReason,
			&i.ApprovalSource,
			&i.SourceRequestID,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetiredDepartments = `-- name: ListRetiredDepartments :many

SELECT
  id,
  code,
  name,
  parent_id,
  successor_department_id,
  valid_from,
  valid_to,
  source,
  source_ou,
  last_synced_at,
  created_at,
  updated_at
FROM departments
WHERE valid_to IS NOT NULL
ORDER BY name
`

// Comments in this file must stay ASCII-only; sqlc v1.31.1 misparses
// non-ASCII comments and splits queries incorrectly.
// ListRetiredDepartments returns the retired departments
// (valid_to NOT NULL), the only valid migration sources for the
// /admin/departments/migrate screen. Ordered by name for the select.
func (q *Queries) ListRetiredDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.QueryContext(ctx, listRetiredDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ParentID,
			&i.SuccessorDepartmentID,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Source,
			&i.SourceOu,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const migrateLicensesToDepartment = `-- name: MigrateLicensesToDepartment :execrows
UPDATE licenses
SET
  owning_department_id = ?1,
  updated_at = CURRENT_TIMESTAMP
WHERE licenses.owning_department_id = ?2
  AND NOT EXISTS (
    SELECT 1 FROM licenses l2
    WHERE l2.product_id = licenses.product_id
      AND l2.owning_department_id = ?1
      AND l2.license_slug = licenses.license_slug
  )
`

type MigrateLicensesToDepartmentParams struct {
	ToDepartmentID   int64
	FromDepartmentID int64
}

// MigrateLicensesToDepartment moves license ownership from the
// retired department to its successor in one statement, skipping the
// rows that would collide with an existing (product_id, license_slug)
// of the destination (they stay with the retired department and are
// reported; the operator renames the slug and re-runs). Re-running is
// safe: already-moved rows no longer match the WHERE clause.
func (q *Queries) MigrateLicensesToDepartment(ctx context.Context, arg MigrateLicensesToDepartmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, migrateLicensesToDepartment, arg.ToDepartmentID, arg.FromDepartmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
