// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package repository

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
  asset_code, hostname, primary_user_id, department_id
) VALUES (
  ?, ?, ?, ?
)
RETURNING
  id,
  asset_code,
  hostname,
  primary_user_id,
  department_id,
  retired_at,
  last_seen_at,
  created_at,
  updated_at
`

type CreateDeviceParams struct {
	AssetCode     string
	Hostname      *string
	PrimaryUserID *int64
	DepartmentID  *int64
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.AssetCode,
		arg.Hostname,
		arg.PrimaryUserID,
		arg.DepartmentID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.AssetCode,
		&i.Hostname,
		&i.PrimaryUserID,
		&i.DepartmentID,
		&i.RetiredAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT
  id,
  asset_code,
  hostname,
  primary_user_id,
  department_id,
  retired_at,
  last_seen_at,
  created_at,
  updated_at
FROM devices
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.AssetCode,
		&i.Hostname,
		&i.PrimaryUserID,
		&i.DepartmentID,
		&i.RetiredAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByAssetCode = `-- name: GetDeviceByAssetCode :one
SELECT
  id, asset_code, hostname, primary_user_id, department_id,
  retired_at, last_seen_at, created_at, updated_at
FROM devices
WHERE asset_code = ?
LIMIT 1
`

func (q *Queries) GetDeviceByAssetCode(ctx context.Context, assetCode string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByAssetCode, assetCode)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.AssetCode,
		&i.Hostname,
		&i.PrimaryUserID,
		&i.DepartmentID,
		&i.RetiredAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT
  id,
  asset_code,
  hostname,
  primary_user_id,
  department_id,
  retired_at,
  last_seen_at,
  created_at,
  updated_at
FROM devices
WHERE retired_at IS NULL
ORDER BY asset_code
LIMIT 200
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.AssetCode,
			&i.Hostname,
			&i.PrimaryUserID,
			&i.DepartmentID,
			&i.RetiredAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesIncludingInactive = `-- name: ListDevicesIncludingInactive :many
SELECT
  id,
  asset_code,
  hostname,
  primary_user_id,
  department_id,
  retired_at,
  last_seen_at,
  created_at,
  updated_at
FROM devices
ORDER BY asset_code
LIMIT 200
`

func (q *Queries) ListDevicesIncludingInactive(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesIncludingInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.AssetCode,
			&i.Hostname,
			&i.PrimaryUserID,
			&i.DepartmentID,
			&i.RetiredAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDevice = `-- name: RestoreDevice :execrows
UPDATE devices
SET
  retired_at = NULL,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND retired_at IS NOT NULL
`

func (q *Queries) RestoreDevice(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchDevices = `-- name: SearchDevices :many
SELECT
  id,
  asset_code,
  hostname,
  primary_user_id,
  department_id,
  retired_at,
  last_seen_at,
  created_at,
  updated_at
FROM devices
WHERE retired_at IS NULL
  AND (asset_code LIKE ?1 OR hostname LIKE ?1)
ORDER BY asset_code
LIMIT 200
`

func (q *Queries) SearchDevices(ctx context.Context, assetCode string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, searchDevices, assetCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.AssetCode,
			&i.Hostname,
			&i.PrimaryUserID,
			&i.DepartmentID,
			&i.RetiredAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDevicesIncludingInactive = `-- name: SearchDevicesIncludingInactive :many
SELECT
  id,
  asset_code,
  hostname,
  primary_user_id,
  department_id,
  retired_at,
  last_seen_at,
  created_at,
  updated_at
FROM devices
WHERE asset_code LIKE ?1 OR hostname LIKE ?1
ORDER BY asset_code
LIMIT 200
`

func (q *Queries) SearchDevicesIncludingInactive(ctx context.Context, assetCode string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, searchDevicesIncludingInactive, assetCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.AssetCode,
			&i.Hostname,
			&i.PrimaryUserID,
			&i.DepartmentID,
			&i.RetiredAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDevice = `-- name: SoftDeleteDevice :execrows
UPDATE devices
SET
  retired_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND retired_at IS NULL
`

func (q *Queries) SoftDeleteDevice(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET
  asset_code = ?,
  hostname = ?,
  primary_user_id = ?,
  department_id = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING
  id,
  asset_code,
  hostname,
  primary_user_id,
  department_id,
  retired_at,
  last_seen_at,
  created_at,
  updated_at
`

type UpdateDeviceParams struct {
	AssetCode     string
	Hostname      *string
	PrimaryUserID *int64
	DepartmentID  *int64
	ID            int64
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDevice,
		arg.AssetCode,
		arg.Hostname,
		arg.PrimaryUserID,
		arg.DepartmentID,
		arg.ID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.AssetCode,
		&i.Hostname,
		&i.PrimaryUserID,
		&i.DepartmentID,
		&i.RetiredAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
