// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: license_documents.sql

package repository

import (
	"context"
)

const createLicenseDocument = `-- name: CreateLicenseDocument :one
INSERT INTO license_documents (
  license_id,
  doc_type,
  stored_path,
  original_filename,
  sha256,
  mime_type,
  size_bytes,
  uploaded_by_app_user_id,
  note
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, license_id, doc_type, stored_path, original_filename, sha256, mime_type, size_bytes, uploaded_at, uploaded_by_app_user_id, note
`

type CreateLicenseDocumentParams struct {
	LicenseID           int64
	DocType             string
	StoredPath          string
	OriginalFilename    string
	Sha256              string
	MimeType            *string
	SizeBytes           *int64
	UploadedByAppUserID *int64
	Note                *string
}

// CreateLicenseDocument inserts one uploaded document row. stored_path is
// the path relative to file_store.base_path with / separators; sha256 and
// mime_type come from the filestore validation (magic-byte sniffing).
func (q *Queries) CreateLicenseDocument(ctx context.Context, arg CreateLicenseDocumentParams) (LicenseDocument, error) {
	row := q.db.QueryRowContext(ctx, createLicenseDocument,
		arg.LicenseID,
		arg.DocType,
		arg.StoredPath,
		arg.OriginalFilename,
		arg.Sha256,
		arg.MimeType,
		arg.SizeBytes,
		arg.UploadedByAppUserID,
		arg.Note,
	)
	var i LicenseDocument
	err := row.Scan(
		&i.ID,
		&i.LicenseID,
		&i.DocType,
		&i.StoredPath,
		&i.OriginalFilename,
		&i.Sha256,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedAt,
		&i.UploadedByAppUserID,
		&i.Note,
	)
	return i, err
}

const getLicenseDocumentByID = `-- name: GetLicenseDocumentByID :one
SELECT id, license_id, doc_type, stored_path, original_filename, sha256, mime_type, size_bytes, uploaded_at, uploaded_by_app_user_id, note FROM license_documents
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetLicenseDocumentByID(ctx context.Context, id int64) (LicenseDocument, error) {
	row := q.db.QueryRowContext(ctx, getLicenseDocumentByID, id)
	var i LicenseDocument
	err := row.Scan(
		&i.ID,
		&i.LicenseID,
		&i.DocType,
		&i.StoredPath,
		&i.OriginalFilename,
		&i.Sha256,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedAt,
		&i.UploadedByAppUserID,
		&i.Note,
	)
	return i, err
}

const listLicenseDocumentsByLicense = `-- name: ListLicenseDocumentsByLicense :many

SELECT id, license_id, doc_type, stored_path, original_filename, sha256, mime_type, size_bytes, uploaded_at, uploaded_by_app_user_id, note FROM license_documents
WHERE license_id = ?
ORDER BY uploaded_at, id
`

// Comments in this file must stay ASCII-only; sqlc v1.31.1 misparses
// non-ASCII comments and splits queries incorrectly.
// ListLicenseDocumentsByLicense returns the documents of one license in
// upload order (uploaded_at ascending, id as a deterministic tiebreaker).
func (q *Queries) ListLicenseDocumentsByLicense(ctx context.Context, licenseID int64) ([]LicenseDocument, error) {
	rows, err := q.db.QueryContext(ctx, listLicenseDocumentsByLicense, licenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LicenseDocument
	for rows.Next() {
		var i LicenseDocument
		if err := rows.Scan(
			&i.ID,
			&i.LicenseID,
			&i.DocType,
			&i.StoredPath,
			&i.OriginalFilename,
			&i.Sha256,
			&i.MimeType,
			&i.SizeBytes,
			&i.UploadedAt,
			&i.UploadedByAppUserID,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLicenseDocumentStoredPath = `-- name: UpdateLicenseDocumentStoredPath :execrows
UPDATE license_documents
SET stored_path = ?
WHERE id = ?
`

type UpdateLicenseDocumentStoredPathParams struct {
	StoredPath string
	ID         int64
}

// UpdateLicenseDocumentStoredPath rewrites the stored_path of one document.
// Used when a license fs_dir_path changes (directory rename on slug change):
// the web layer re-prefixes each matching path so the DB keeps pointing at
// the moved files.
func (q *Queries) UpdateLicenseDocumentStoredPath(ctx context.Context, arg UpdateLicenseDocumentStoredPathParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLicenseDocumentStoredPath, arg.StoredPath, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
