// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: licenses.sql

package repository

import (
	"context"
	"time"
)

const createLicense = `-- name: CreateLicense :one
INSERT INTO licenses (
  product_id,
  owning_department_id,
  license_slug,
  display_name,
  total_count,
  count_unit,
  contract_type,
  purchased_at,
  started_at,
  expires_at,
  vendor_order_no,
  purchaser,
  unit_price,
  currency,
  product_keys,
  fs_dir_path,
  note
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, product_id, owning_department_id, license_slug, display_name, total_count, count_unit, contract_type, purchased_at, started_at, expires_at, vendor_order_no, purchaser, unit_price, currency, product_keys, fs_dir_path, note, created_at, updated_at
`

type CreateLicenseParams struct {
	ProductID          int64
	OwningDepartmentID int64
	LicenseSlug        string
	DisplayName        string
	TotalCount         *int64
	CountUnit          string
	ContractType       string
	PurchasedAt        *time.Time
	StartedAt          *time.Time
	ExpiresAt          *time.Time
	VendorOrderNo      *string
	Purchaser          *string
	UnitPrice          *int64
	Currency           *string
	ProductKeys        *string
	FsDirPath          string
	Note               *string
}

func (q *Queries) CreateLicense(ctx context.Context, arg CreateLicenseParams) (License, error) {
	row := q.db.QueryRowContext(ctx, createLicense,
		arg.ProductID,
		arg.OwningDepartmentID,
		arg.LicenseSlug,
		arg.DisplayName,
		arg.TotalCount,
		arg.CountUnit,
		arg.ContractType,
		arg.PurchasedAt,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.VendorOrderNo,
		arg.Purchaser,
		arg.UnitPrice,
		arg.Currency,
		arg.ProductKeys,
		arg.FsDirPath,
		arg.Note,
	)
	var i License
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OwningDepartmentID,
		&i.LicenseSlug,
		&i.DisplayName,
		&i.TotalCount,
		&i.CountUnit,
		&i.ContractType,
		&i.PurchasedAt,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.VendorOrderNo,
		&i.Purchaser,
		&i.UnitPrice,
		&i.Currency,
		&i.ProductKeys,
		&i.FsDirPath,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLicenseByID = `-- name: GetLicenseByID :one
SELECT
  l.id, l.product_id, l.owning_department_id, l.license_slug, l.display_name, l.total_count, l.count_unit, l.contract_type, l.purchased_at, l.started_at, l.expires_at, l.vendor_order_no, l.purchaser, l.unit_price, l.currency, l.product_keys, l.fs_dir_path, l.note, l.created_at, l.updated_at,
  p.canonical_name AS product_name,
  ve.name AS vendor_name,
  d.name AS department_name
FROM licenses l
JOIN products p ON p.id = l.product_id
JOIN vendors ve ON ve.id = p.vendor_id
JOIN departments d ON d.id = l.owning_department_id
WHERE l.id = ?
LIMIT 1
`

type GetLicenseByIDRow struct {
	ID                 int64
	ProductID          int64
	OwningDepartmentID int64
	LicenseSlug        string
	DisplayName        string
	TotalCount         *int64
	CountUnit          string
	ContractType       string
	PurchasedAt        *time.Time
	StartedAt          *time.Time
	ExpiresAt          *time.Time
	VendorOrderNo      *string
	Purchaser          *string
	UnitPrice          *int64
	Currency           *string
	ProductKeys        *string
	FsDirPath          string
	Note               *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	ProductName        string
	VendorName         string
	DepartmentName     string
}

func (q *Queries) GetLicenseByID(ctx context.Context, id int64) (GetLicenseByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLicenseByID, id)
	var i GetLicenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OwningDepartmentID,
		&i.LicenseSlug,
		&i.DisplayName,
		&i.TotalCount,
		&i.CountUnit,
		&i.ContractType,
		&i.PurchasedAt,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.VendorOrderNo,
		&i.Purchaser,
		&i.UnitPrice,
		&i.Currency,
		&i.ProductKeys,
		&i.FsDirPath,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductName,
		&i.VendorName,
		&i.DepartmentName,
	)
	return i, err
}

const listLicenses = `-- name: ListLicenses :many

SELECT
  l.id, l.product_id, l.owning_department_id, l.license_slug,
  l.display_name, l.total_count, l.count_unit, l.contract_type,
  l.purchased_at, l.started_at, l.expires_at, l.vendor_order_no,
  l.purchaser, l.unit_price, l.currency, l.fs_dir_path, l.note,
  l.created_at, l.updated_at,
  p.canonical_name AS product_name,
  ve.name AS vendor_name,
  d.name AS department_name
FROM licenses l
JOIN products p ON p.id = l.product_id
JOIN vendors ve ON ve.id = p.vendor_id
JOIN departments d ON d.id = l.owning_department_id
WHERE (CAST(?1 AS INTEGER) = 1 OR l.expires_at IS NULL OR l.expires_at >= date('now'))
ORDER BY l.expires_at IS NULL, l.expires_at, l.id
`

type ListLicensesRow struct {
	ID                 int64
	ProductID          int64
	OwningDepartmentID int64
	LicenseSlug        string
	DisplayName        string
	TotalCount         *int64
	CountUnit          string
	ContractType       string
	PurchasedAt        *time.Time
	StartedAt          *time.Time
	ExpiresAt          *time.Time
	VendorOrderNo      *string
	Purchaser          *string
	UnitPrice          *int64
	Currency           *string
	FsDirPath          string
	Note               *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	ProductName        string
	VendorName         string
	DepartmentName     string
}

// Comments in this file must stay ASCII-only; sqlc v1.31.1 misparses
// non-ASCII comments and splits queries incorrectly.
// ListLicenses returns display rows joined with product, vendor and
// owning department names. The first parameter is an include-expired
// flag: pass 1 to list every license, any other value to list only
// active ones (expires_at IS NULL or in the future). Rows are ordered
// by expiry ascending with never-expiring (NULL) rows last.
// product_keys is intentionally excluded from list rows: they are handed
// to the view layer as-is and must never carry secret material.
func (q *Queries) ListLicenses(ctx context.Context, dollar_1 int64) ([]ListLicensesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLicenses, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLicensesRow
	for rows.Next() {
		var i ListLicensesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OwningDepartmentID,
			&i.LicenseSlug,
			&i.DisplayName,
			&i.TotalCount,
			&i.CountUnit,
			&i.ContractType,
			&i.PurchasedAt,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.VendorOrderNo,
			&i.Purchaser,
			&i.UnitPrice,
			&i.Currency,
			&i.FsDirPath,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.VendorName,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLicense = `-- name: UpdateLicense :execrows
UPDATE licenses
SET
  product_id = ?,
  owning_department_id = ?,
  license_slug = ?,
  display_name = ?,
  total_count = ?,
  count_unit = ?,
  contract_type = ?,
  purchased_at = ?,
  started_at = ?,
  expires_at = ?,
  vendor_order_no = ?,
  purchaser = ?,
  unit_price = ?,
  currency = ?,
  product_keys = ?,
  fs_dir_path = ?,
  note = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateLicenseParams struct {
	ProductID          int64
	OwningDepartmentID int64
	LicenseSlug        string
	DisplayName        string
	TotalCount         *int64
	CountUnit          string
	ContractType       string
	PurchasedAt        *time.Time
	StartedAt          *time.Time
	ExpiresAt          *time.Time
	VendorOrderNo      *string
	Purchaser          *string
	UnitPrice          *int64
	Currency           *string
	ProductKeys        *string
	FsDirPath          string
	Note               *string
	ID                 int64
}

func (q *Queries) UpdateLicense(ctx context.Context, arg UpdateLicenseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLicense,
		arg.ProductID,
		arg.OwningDepartmentID,
		arg.LicenseSlug,
		arg.DisplayName,
		arg.TotalCount,
		arg.CountUnit,
		arg.ContractType,
		arg.PurchasedAt,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.VendorOrderNo,
		arg.Purchaser,
		arg.UnitPrice,
		arg.Currency,
		arg.ProductKeys,
		arg.FsDirPath,
		arg.Note,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
