// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"
)

type AppSetting struct {
	Key                string
	Value              *string
	UpdatedAt          time.Time
	UpdatedByAppUserID *int64
}

type AppUser struct {
	ID           int64
	Username     string
	PasswordHash *string
	LinkedUserID *int64
	NotifyEmail  *string
	AuthType     string
	DisabledAt   *time.Time
	LastLoginAt  *time.Time
	CreatedAt    time.Time
}

type ApprovalRequest struct {
	ID                    int64
	ProductID             int64
	DepartmentID          int64
	RequesterEmployeeCode *string
	RequesterEmail        *string
	RequestedAt           time.Time
	Purpose               *string
	Status                string
	DecidedAt             *time.Time
	DecidedByAppUserID    *int64
	DecisionNote          *string
	ResultingApprovalID   *int64
}

type ApprovalScopeDevice struct {
	ID         int64
	ApprovalID int64
	DeviceID   int64
}

type ApprovalScopeUser struct {
	ID         int64
	ApprovalID int64
	UserID     int64
}

type AuditLog struct {
	ID         int64
	AppUserID  *int64
	Action     string
	EntityType string
	EntityID   *int64
	DiffJson   *string
	OccurredAt time.Time
}

type Department struct {
	ID                    int64
	Code                  string
	Name                  string
	ParentID              *int64
	SuccessorDepartmentID *int64
	ValidFrom             *time.Time
	ValidTo               *time.Time
	Source                string
	SourceOu              *string
	LastSyncedAt          *time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type DepartmentProductApproval struct {
	ID                  int64
	DepartmentID        int64
	ProductID           int64
	Status              string
	ScopeType           string
	Conditions          *string
	ApprovedByAppUserID *int64
	ApprovedAt          *time.Time
	ExpiresAt           *time.Time
	RevokedAt           *time.Time
	RevokedByAppUserID  *int64
	RevokeReason        *string
	ApprovalSource      string
	SourceRequestID     *int64
	Note                *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Device struct {
	ID            int64
	AssetCode     string
	Hostname      *string
	PrimaryUserID *int64
	DepartmentID  *int64
	RetiredAt     *time.Time
	LastSeenAt    *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type DeviceAssignment struct {
	ID         int64
	LicenseID  int64
	DeviceID   int64
	AssignedAt time.Time
	RevokedAt  *time.Time
	Note       *string
}

type ImportLog struct {
	ID           int64
	SourceType   string
	SourceFile   string
	ImportedAt   time.Time
	RowCount     *int64
	SuccessCount *int64
	ErrorCount   *int64
	Status       string
	ErrorLog     *string
}

type Installation struct {
	ID              int64
	DeviceID        int64
	ProductID       int64
	Version         *string
	FirstDetectedAt time.Time
	LastDetectedAt  time.Time
	LastUsedAt      *time.Time
	UninstalledAt   *time.Time
}

type InventoryAudit struct {
	ID                   int64
	DepartmentID         int64
	FiscalPeriod         string
	InitiatedAt          time.Time
	InitiatedByAppUserID *int64
	DueDate              *time.Time
	Status               string
	CompletedAt          *time.Time
	CompletedByAppUserID *int64
	ResultNote           *string
	SnapshotJson         *string
}

type License struct {
	ID                 int64
	ProductID          int64
	OwningDepartmentID int64
	LicenseSlug        string
	DisplayName        string
	TotalCount         *int64
	CountUnit          string
	ContractType       string
	PurchasedAt        *time.Time
	StartedAt          *time.Time
	ExpiresAt          *time.Time
	VendorOrderNo      *string
	Purchaser          *string
	UnitPrice          *int64
	Currency           *string
	ProductKeys        *string
	FsDirPath          string
	Note               *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type LicenseDocument struct {
	ID                  int64
	LicenseID           int64
	DocType             string
	StoredPath          string
	OriginalFilename    string
	Sha256              string
	MimeType            *string
	SizeBytes           *int64
	UploadedAt          time.Time
	UploadedByAppUserID *int64
	Note                *string
}

type Notification struct {
	ID                int64
	Kind              string
	Channel           string
	Recipient         string
	Subject           *string
	Body              *string
	RelatedEntityType *string
	RelatedEntityID   *int64
	Status            string
	RetryCount        int64
	LastAttemptedAt   *time.Time
	LastError         *string
	SentAt            *time.Time
	CreatedAt         time.Time
}

type Product struct {
	ID                    int64
	VendorID              int64
	CanonicalName         string
	Edition               *string
	SoftwareType          string
	LicenseRequired       *bool
	DefaultApprovalStatus string
	CanonicalDownloadUrl  *string
	ServiceAdminUrl       *string
	LicenseTermsUrl       *string
	Note                  *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type ProductAlias struct {
	ID        int64
	ProductID int64
	AliasName string
	Source    string
	CreatedAt time.Time
}

type ProductVersionAdvisory struct {
	ID                   int64
	ProductID            int64
	AdvisoryCode         *string
	Severity             *string
	AffectedVersionRange string
	FixedVersion         *string
	Summary              *string
	DetailUrl            *string
	PublishedAt          *time.Time
	NotifiedAt           *time.Time
	CreatedAt            time.Time
}

type RawInstallation struct {
	ID                int64
	ImportLogID       int64
	DeviceAssetCode   string
	RawProductName    string
	RawVendorName     *string
	Version           *string
	DetectedAt        *time.Time
	LastUsedAt        *time.Time
	ResolvedDeviceID  *int64
	ResolvedProductID *int64
	Status            string
	ResolvedAt        *time.Time
	CreatedAt         time.Time
}

type User struct {
	ID            int64
	EmployeeCode  string
	Username      *string
	Name          string
	Email         *string
	DepartmentID  *int64
	DeactivatedAt *time.Time
	Source        string
	SourceDn      *string
	AdModifiedAt  *time.Time
	LastSyncedAt  *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UserAssignment struct {
	ID                int64
	LicenseID         int64
	UserID            int64
	ExternalAccountID *string
	ProvisionedAt     *time.Time
	DeprovisionedAt   *time.Time
	AssignedAt        time.Time
	RevokedAt         *time.Time
	Note              *string
}

type UserDepartmentRole struct {
	ID           int64
	AppUserID    int64
	DepartmentID *int64
	Role         string
	GrantedAt    time.Time
	RevokedAt    *time.Time
}

type VLicenseUsage struct {
	ProductID           int64
	CanonicalName       string
	VendorName          string
	TotalOwned          int64
	InstalledCount      int64
	UserAssignedCount   int64
	DeviceAssignedCount int64
}

type Vendor struct {
	ID        int64
	Name      string
	Url       *string
	Note      *string
	CreatedAt time.Time
	UpdatedAt time.Time
}
