// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package repository

import (
	"context"
	"time"
)

const countNotificationsByKindOnDay = `-- name: CountNotificationsByKindOnDay :one
SELECT count(*) FROM notifications
WHERE kind = ?
  AND substr(CAST(created_at AS TEXT), 1, 10) = CAST(?2 AS TEXT)
`

type CountNotificationsByKindOnDayParams struct {
	Kind string
	Day  string
}

// CountNotificationsByKindOnDay supports the daily gave_up summary
// dedup: pass kind='gave_up_summary' and the UTC day as a YYYY-MM-DD
// string. The date-prefix comparison via substr works for both storage
// formats (CURRENT_TIMESTAMP "YYYY-MM-DD HH:MM:SS" and the Go driver's
// "... +0000 UTC"); binding a raw time.Time instead would miss rows
// created exactly at midnight because of the string format difference.
// Equality (not >=) is used so that a future-dated row (clock skew)
// cannot permanently suppress every later daily summary.
// CountSentNotificationForEvent cannot be reused because summary rows
// have NULL related_entity_type/id.
func (q *Queries) CountNotificationsByKindOnDay(ctx context.Context, arg CountNotificationsByKindOnDayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotificationsByKindOnDay, arg.Kind, arg.Day)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSentNotificationForEvent = `-- name: CountSentNotificationForEvent :one
SELECT count(*) FROM notifications
WHERE kind = ?
  AND channel = ?
  AND related_entity_type = ?
  AND related_entity_id = ?
  AND status = 'sent'
`

type CountSentNotificationForEventParams struct {
	Kind              string
	Channel           string
	RelatedEntityType *string
	RelatedEntityID   *int64
}

// CountSentNotificationForEvent implements the duplicate-suppression
// key (kind, channel, related_entity_type, related_entity_id) from spec
// 5.9: when a sent record already exists for the event on the channel,
// no new record is created. The channel is part of the key so that a
// multi partial success re-sends only on channels that have not
// succeeded yet. Callers pass non-NULL related_* values.
func (q *Queries) CountSentNotificationForEvent(ctx context.Context, arg CountSentNotificationForEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSentNotificationForEvent,
		arg.Kind,
		arg.Channel,
		arg.RelatedEntityType,
		arg.RelatedEntityID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSupersededFailedNotifications = `-- name: CountSupersededFailedNotifications :one
SELECT count(*) FROM notifications n
WHERE n.status = 'failed'
  AND n.retry_count < ?
  AND EXISTS (
    SELECT 1 FROM notifications s
    WHERE s.status = 'sent'
      AND s.kind = n.kind
      AND s.channel = n.channel
      AND s.recipient = n.recipient
      AND s.related_entity_type IS n.related_entity_type
      AND s.related_entity_id IS n.related_entity_id
  )
`

// CountSupersededFailedNotifications counts the failed rows that
// ListFailedNotificationsForRetry excludes by the sent-exists rule, so
// the retry run can report them as skipped_superseded.
func (q *Queries) CountSupersededFailedNotifications(ctx context.Context, retryCount int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSupersededFailedNotifications, retryCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (
  kind,
  channel,
  recipient,
  subject,
  body,
  related_entity_type,
  related_entity_id
) VALUES (
  ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, kind, channel, recipient, subject, body,
  related_entity_type, related_entity_id, status, retry_count,
  last_attempted_at, last_error, sent_at, created_at
`

type CreateNotificationParams struct {
	Kind              string
	Channel           string
	Recipient         string
	Subject           *string
	Body              *string
	RelatedEntityType *string
	RelatedEntityID   *int64
}

// Queries for appmgr-notify (spec 5.9): notifications table lifecycle,
// license expiry detection and recipient resolution.
// Comments in this file must stay ASCII-only; sqlc v1.31.1 misparses
// non-ASCII comments and splits queries incorrectly.
// CreateNotification inserts a pending notification record. Spec 5.9
// requires a record to exist before any send attempt.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.Kind,
		arg.Channel,
		arg.Recipient,
		arg.Subject,
		arg.Body,
		arg.RelatedEntityType,
		arg.RelatedEntityID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.Status,
		&i.RetryCount,
		&i.LastAttemptedAt,
		&i.LastError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementNotificationRetry = `-- name: IncrementNotificationRetry :execrows
UPDATE notifications
SET retry_count = retry_count + 1,
    status = ?1,
    last_attempted_at = CURRENT_TIMESTAMP,
    last_error = ?2
WHERE id = ?3
`

type IncrementNotificationRetryParams struct {
	Status    string
	LastError *string
	ID        int64
}

// IncrementNotificationRetry records the outcome of one failed retry
// attempt: bumps retry_count and sets status as decided by the caller
// ('failed' to keep retrying, 'gave_up' when retry_count reaches
// notification_max_retry). Successful retries use MarkNotificationSent.
func (q *Queries) IncrementNotificationRetry(ctx context.Context, arg IncrementNotificationRetryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementNotificationRetry, arg.Status, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listFailedNotificationsForRetry = `-- name: ListFailedNotificationsForRetry :many
SELECT id, kind, channel, recipient, subject, body,
  related_entity_type, related_entity_id, status, retry_count,
  last_attempted_at, last_error, sent_at, created_at
FROM notifications n
WHERE n.status = 'failed'
  AND n.retry_count < ?
  AND NOT EXISTS (
    SELECT 1 FROM notifications s
    WHERE s.status = 'sent'
      AND s.kind = n.kind
      AND s.channel = n.channel
      AND s.recipient = n.recipient
      AND s.related_entity_type IS n.related_entity_type
      AND s.related_entity_id IS n.related_entity_id
  )
ORDER BY n.id
`

// ListFailedNotificationsForRetry returns failed notifications still
// eligible for retry. Rows are excluded (superseded) when a sent record
// already exists for the same (kind, channel, recipient, related_*):
// the daily run re-creates events whose only records are failed (spec
// dedup checks sent only), so once that re-created record is delivered,
// retrying the stale failed row would double-send. IS is used for the
// related_* comparison because summary rows carry NULLs and '=' never
// matches NULL.
func (q *Queries) ListFailedNotificationsForRetry(ctx context.Context, retryCount int64) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listFailedNotificationsForRetry, retryCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Channel,
			&i.Recipient,
			&i.Subject,
			&i.Body,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.Status,
			&i.RetryCount,
			&i.LastAttemptedAt,
			&i.LastError,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLicenseManagerEmailsForDepartment = `-- name: ListLicenseManagerEmailsForDepartment :many
SELECT DISTINCT
  au.id AS app_user_id,
  au.username,
  au.notify_email,
  u.email AS linked_user_email
FROM user_department_roles r
JOIN app_users au ON au.id = r.app_user_id
LEFT JOIN users u ON u.id = au.linked_user_id
WHERE r.role = 'license_manager'
  AND r.department_id = ?
  AND r.revoked_at IS NULL
  AND au.disabled_at IS NULL
ORDER BY au.id
`

type ListLicenseManagerEmailsForDepartmentRow struct {
	AppUserID       int64
	Username        string
	NotifyEmail     *string
	LinkedUserEmail *string
}

// ListLicenseManagerEmailsForDepartment returns active license_manager
// app users for a department with their email candidates. Recipient
// resolution order (spec 5.9): notify_email first, then the linked
// user's email; callers warn and skip when both are empty. DISTINCT
// guards against duplicate active role rows (the UNIQUE constraint
// treats NULL revoked_at values as distinct in SQLite).
func (q *Queries) ListLicenseManagerEmailsForDepartment(ctx context.Context, departmentID *int64) ([]ListLicenseManagerEmailsForDepartmentRow, error) {
	rows, err := q.db.QueryContext(ctx, listLicenseManagerEmailsForDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLicenseManagerEmailsForDepartmentRow
	for rows.Next() {
		var i ListLicenseManagerEmailsForDepartmentRow
		if err := rows.Scan(
			&i.AppUserID,
			&i.Username,
			&i.NotifyEmail,
			&i.LinkedUserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLicensesExpiringOn = `-- name: ListLicensesExpiringOn :many
SELECT
  l.id,
  l.display_name,
  l.expires_at,
  l.owning_department_id,
  p.canonical_name AS product_name,
  ve.name AS vendor_name,
  d.name AS department_name
FROM licenses l
JOIN products p ON p.id = l.product_id
JOIN vendors ve ON ve.id = p.vendor_id
JOIN departments d ON d.id = l.owning_department_id
WHERE l.expires_at IS NOT NULL
  AND substr(CAST(l.expires_at AS TEXT), 1, 10) = CAST(?1 AS TEXT)
ORDER BY l.id
`

type ListLicensesExpiringOnRow struct {
	ID                 int64
	DisplayName        string
	ExpiresAt          *time.Time
	OwningDepartmentID int64
	ProductName        string
	VendorName         string
	DepartmentName     string
}

// ListLicensesExpiringOn returns licenses whose expires_at falls on the
// given UTC date ('YYYY-MM-DD', computed by the caller as today+N),
// joined with product, vendor and owning department names for the
// notification body. The comparison uses substr(...,1,10) instead of
// date(expires_at): the Go sqlite driver stores time.Time values in Go's
// time.String() format ("2026-08-08 00:00:00 +0000 UTC"), which SQLite's
// date() cannot parse (it returns NULL, so no row would ever match).
// substr works for both that format and CURRENT_TIMESTAMP-style text.
func (q *Queries) ListLicensesExpiringOn(ctx context.Context, expiresOn string) ([]ListLicensesExpiringOnRow, error) {
	rows, err := q.db.QueryContext(ctx, listLicensesExpiringOn, expiresOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLicensesExpiringOnRow
	for rows.Next() {
		var i ListLicensesExpiringOnRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.ExpiresAt,
			&i.OwningDepartmentID,
			&i.ProductName,
			&i.VendorName,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemAdminEmails = `-- name: ListSystemAdminEmails :many
SELECT DISTINCT
  au.id AS app_user_id,
  au.username,
  au.notify_email,
  u.email AS linked_user_email
FROM user_department_roles r
JOIN app_users au ON au.id = r.app_user_id
LEFT JOIN users u ON u.id = au.linked_user_id
WHERE r.role = 'system_admin'
  AND r.revoked_at IS NULL
  AND au.disabled_at IS NULL
ORDER BY au.id
`

type ListSystemAdminEmailsRow struct {
	AppUserID       int64
	Username        string
	NotifyEmail     *string
	LinkedUserEmail *string
}

// ListSystemAdminEmails returns active system_admin app users with
// their email candidates. Used as fallback recipients when a
// department has no license_manager, and for the gave_up daily summary.
func (q *Queries) ListSystemAdminEmails(ctx context.Context) ([]ListSystemAdminEmailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSystemAdminEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemAdminEmailsRow
	for rows.Next() {
		var i ListSystemAdminEmailsRow
		if err := rows.Scan(
			&i.AppUserID,
			&i.Username,
			&i.NotifyEmail,
			&i.LinkedUserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsummarizedGaveUp = `-- name: ListUnsummarizedGaveUp :many
SELECT id, kind, channel, recipient, subject, body,
  related_entity_type, related_entity_id, status, retry_count,
  last_attempted_at, last_error, sent_at, created_at
FROM notifications
WHERE status = 'gave_up'
  AND kind != 'gave_up_summary'
  AND last_attempted_at > COALESCE(
    (SELECT MAX(s.created_at) FROM notifications s
     WHERE s.kind = 'gave_up_summary'
       AND s.status = 'sent'),
    '1970-01-01 00:00:00')
ORDER BY id
`

// ListUnsummarizedGaveUp returns gave_up notifications not yet covered
// by a delivered gave_up_summary: rows whose last attempt happened
// after the most recent *sent* summary was created (all gave_up rows
// when no sent summary exists yet). gave_up rows always carry
// last_attempted_at because the retry flow sets it on every attempt.
// The checkpoint deliberately ignores non-sent summaries: a failed
// summary never reached the admins, so letting it advance the
// checkpoint would hide those gave_up rows from every future summary.
// A failed summary is also re-sent by --retry-failed with its original
// body; if that retry later succeeds after the next daily run already
// re-summarized, the same rows can be reported twice. Duplicated
// listing is accepted as safer than permanent omission.
func (q *Queries) ListUnsummarizedGaveUp(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listUnsummarizedGaveUp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Channel,
			&i.Recipient,
			&i.Subject,
			&i.Body,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.Status,
			&i.RetryCount,
			&i.LastAttemptedAt,
			&i.LastError,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationFailed = `-- name: MarkNotificationFailed :execrows
UPDATE notifications
SET status = 'failed',
    last_attempted_at = CURRENT_TIMESTAMP,
    last_error = ?
WHERE id = ?
`

type MarkNotificationFailedParams struct {
	LastError *string
	ID        int64
}

// MarkNotificationFailed records a failed initial send. retry_count is
// intentionally not incremented here: it counts --retry-failed attempts
// only, so a record becomes gave_up after notification_max_retry
// retries regardless of the initial failure.
func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationFailed, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markNotificationSent = `-- name: MarkNotificationSent :execrows
UPDATE notifications
SET status = 'sent',
    sent_at = CURRENT_TIMESTAMP,
    last_attempted_at = CURRENT_TIMESTAMP,
    last_error = NULL
WHERE id = ?
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
