// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_aliases.sql

package repository

import (
	"context"
)

const createAlias = `-- name: CreateAlias :one
INSERT INTO product_aliases (
  product_id,
  alias_name,
  source
) VALUES (
  ?, ?, 'manual'
)
RETURNING
  id,
  product_id,
  alias_name,
  source,
  created_at
`

type CreateAliasParams struct {
	ProductID int64
	AliasName string
}

func (q *Queries) CreateAlias(ctx context.Context, arg CreateAliasParams) (ProductAlias, error) {
	row := q.db.QueryRowContext(ctx, createAlias, arg.ProductID, arg.AliasName)
	var i ProductAlias
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AliasName,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlias = `-- name: DeleteAlias :exec
DELETE FROM product_aliases WHERE id = ?
`

func (q *Queries) DeleteAlias(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlias, id)
	return err
}

const listAliasesByProduct = `-- name: ListAliasesByProduct :many
SELECT
  id,
  product_id,
  alias_name,
  source,
  created_at
FROM product_aliases
WHERE product_id = ?
ORDER BY alias_name
`

func (q *Queries) ListAliasesByProduct(ctx context.Context, productID int64) ([]ProductAlias, error) {
	rows, err := q.db.QueryContext(ctx, listAliasesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAlias
	for rows.Next() {
		var i ProductAlias
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.AliasName,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
