// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prune.sql

package repository

import (
	"context"
	"time"
)

const countPrunableAuditLogs = `-- name: CountPrunableAuditLogs :one
SELECT count(*) FROM audit_logs
WHERE occurred_at < ?
`

func (q *Queries) CountPrunableAuditLogs(ctx context.Context, occurredAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrunableAuditLogs, occurredAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrunableImportLogs = `-- name: CountPrunableImportLogs :one
SELECT count(*) FROM import_logs
WHERE imported_at < ?
  AND NOT EXISTS (
    SELECT 1 FROM raw_installations r
    WHERE r.import_log_id = import_logs.id
      AND r.created_at >= ?
  )
`

type CountPrunableImportLogsParams struct {
	ImportedAt time.Time
	CreatedAt  time.Time
}

// CountPrunableImportLogs intentionally differs from PruneImportLogs.
// The real run deletes raw_installations before import_logs, so a parent
// whose children are all prunable raw rows is deleted in the same run.
// To predict the post-run state, exclude only parents keeping a child
// that survives this run. Bind the raw cutoff to the second parameter.
// (Comment kept ASCII-only; sqlc v1.31.1 misparses non-ASCII comments.)
func (q *Queries) CountPrunableImportLogs(ctx context.Context, arg CountPrunableImportLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrunableImportLogs, arg.ImportedAt, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrunableRawInstallations = `-- name: CountPrunableRawInstallations :one
SELECT count(*) FROM raw_installations
WHERE created_at < ?
`

func (q *Queries) CountPrunableRawInstallations(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrunableRawInstallations, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrunableSentNotifications = `-- name: CountPrunableSentNotifications :one
SELECT count(*) FROM notifications
WHERE sent_at IS NOT NULL AND sent_at < ?
`

func (q *Queries) CountPrunableSentNotifications(ctx context.Context, sentAt *time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrunableSentNotifications, sentAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const pruneAuditLogs = `-- name: PruneAuditLogs :execrows
DELETE FROM audit_logs
WHERE occurred_at < ?
`

func (q *Queries) PruneAuditLogs(ctx context.Context, occurredAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAuditLogs, occurredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneImportLogs = `-- name: PruneImportLogs :execrows
DELETE FROM import_logs
WHERE imported_at < ?
  AND NOT EXISTS (SELECT 1 FROM raw_installations r WHERE r.import_log_id = import_logs.id)
`

func (q *Queries) PruneImportLogs(ctx context.Context, importedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneImportLogs, importedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneRawInstallations = `-- name: PruneRawInstallations :execrows
DELETE FROM raw_installations
WHERE created_at < ?
`

func (q *Queries) PruneRawInstallations(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneRawInstallations, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneSentNotifications = `-- name: PruneSentNotifications :execrows
DELETE FROM notifications
WHERE sent_at IS NOT NULL AND sent_at < ?
`

func (q *Queries) PruneSentNotifications(ctx context.Context, sentAt *time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneSentNotifications, sentAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
