// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_department_roles.sql

package repository

import (
	"context"
)

const createUserDepartmentRole = `-- name: CreateUserDepartmentRole :one
INSERT INTO user_department_roles (
  app_user_id,
  department_id,
  role
) VALUES (
  ?, ?, ?
)
RETURNING
  id,
  app_user_id,
  department_id,
  role,
  granted_at,
  revoked_at
`

type CreateUserDepartmentRoleParams struct {
	AppUserID    int64
	DepartmentID *int64
	Role         string
}

func (q *Queries) CreateUserDepartmentRole(ctx context.Context, arg CreateUserDepartmentRoleParams) (UserDepartmentRole, error) {
	row := q.db.QueryRowContext(ctx, createUserDepartmentRole, arg.AppUserID, arg.DepartmentID, arg.Role)
	var i UserDepartmentRole
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.DepartmentID,
		&i.Role,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}
