// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_department_roles.sql

package repository

import (
	"context"
)

const createUserDepartmentRole = `-- name: CreateUserDepartmentRole :one
INSERT INTO user_department_roles (
  app_user_id,
  department_id,
  role
) VALUES (
  ?, ?, ?
)
RETURNING
  id,
  app_user_id,
  department_id,
  role,
  granted_at,
  revoked_at
`

type CreateUserDepartmentRoleParams struct {
	AppUserID    int64
	DepartmentID *int64
	Role         string
}

func (q *Queries) CreateUserDepartmentRole(ctx context.Context, arg CreateUserDepartmentRoleParams) (UserDepartmentRole, error) {
	row := q.db.QueryRowContext(ctx, createUserDepartmentRole, arg.AppUserID, arg.DepartmentID, arg.Role)
	var i UserDepartmentRole
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.DepartmentID,
		&i.Role,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveRolesForAppUser = `-- name: ListActiveRolesForAppUser :many
SELECT
  role,
  department_id
FROM user_department_roles
WHERE app_user_id = ?
  AND revoked_at IS NULL
`

type ListActiveRolesForAppUserRow struct {
	Role         string
	DepartmentID *int64
}

func (q *Queries) ListActiveRolesForAppUser(ctx context.Context, appUserID int64) ([]ListActiveRolesForAppUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRolesForAppUser, appUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRolesForAppUserRow
	for rows.Next() {
		var i ListActiveRolesForAppUserRow
		if err := rows.Scan(&i.Role, &i.DepartmentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
