// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendors.sql

package repository

import (
	"context"
)

const countProductsByVendor = `-- name: CountProductsByVendor :one
SELECT COUNT(*) AS count
FROM products
WHERE vendor_id = ?
`

func (q *Queries) CountProductsByVendor(ctx context.Context, vendorID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsByVendor, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (
  name,
  url,
  note
) VALUES (
  ?, ?, ?
)
RETURNING
  id,
  name,
  url,
  note,
  created_at,
  updated_at
`

type CreateVendorParams struct {
	Name string
	Url  *string
	Note *string
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, createVendor, arg.Name, arg.Url, arg.Note)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVendor = `-- name: DeleteVendor :exec
DELETE FROM vendors WHERE id = ?
`

func (q *Queries) DeleteVendor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVendor, id)
	return err
}

const getVendor = `-- name: GetVendor :one
SELECT
  id,
  name,
  url,
  note,
  created_at,
  updated_at
FROM vendors
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetVendor(ctx context.Context, id int64) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendor, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVendors = `-- name: ListVendors :many
SELECT
  id,
  name,
  url,
  note,
  created_at,
  updated_at
FROM vendors
ORDER BY name
LIMIT 200
`

func (q *Queries) ListVendors(ctx context.Context) ([]Vendor, error) {
	rows, err := q.db.QueryContext(ctx, listVendors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vendor
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVendors = `-- name: SearchVendors :many
SELECT
  id,
  name,
  url,
  note,
  created_at,
  updated_at
FROM vendors
WHERE name LIKE ?1
ORDER BY name
LIMIT 200
`

func (q *Queries) SearchVendors(ctx context.Context, name string) ([]Vendor, error) {
	rows, err := q.db.QueryContext(ctx, searchVendors, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vendor
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors
SET
  name = ?,
  url = ?,
  note = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING
  id,
  name,
  url,
  note,
  created_at,
  updated_at
`

type UpdateVendorParams struct {
	Name string
	Url  *string
	Note *string
	ID   int64
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, updateVendor,
		arg.Name,
		arg.Url,
		arg.Note,
		arg.ID,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
