// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
// Package export は /admin/export (仕様 §5.10) の templ ビュー。

// エクスポート生成本体は internal/export、audit 記録は web 層が持ち、

// 本パッケージは表示のみ。

package export

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/tagawa0525/app_man/internal/handler/middleware"
	"github.com/tagawa0525/app_man/internal/view/layout"
)

func Index(role middleware.Role) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"page-admin-export\"><header class=\"page-header\"><h1>エクスポート</h1></header><p>本システムの全データを取り出します (仕様 §5.10)。ダウンロード操作は監査ログ (audit_logs) に記録されます。</p><h2>Excel エクスポート</h2><p>業務データ 10 テーブル (ベンダー / 製品 / 部署 / ユーザ / 端末 / ライセンス / 割当 / 承認 / 設定値) を 1 シート 1 テーブルの xlsx で出力します。論理削除済みの行も含む全件です。</p><form method=\"post\" action=\"/admin/export/excel\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = layout.CSRFInput(middleware.CSRFTokenFrom(ctx)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<label><input type=\"checkbox\" name=\"include_keys\"> ライセンスキーを含める (含めたことが監査ログに記録されます)</label> <button type=\"submit\" class=\"btn\">Excel をダウンロード</button></form><h2>ZIP 一括エクスポート</h2><p>DB スナップショット (db-snapshot.db) と全ライセンス証書 + meta.yml (licenses/ ツリー) をまとめた ZIP を出力します。バックアップと同等の機微データを含むため取り扱いに注意してください。</p><form method=\"post\" action=\"/admin/export/zip\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = layout.CSRFInput(middleware.CSRFTokenFrom(ctx)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<button type=\"submit\" class=\"btn\">ZIP をダウンロード</button></form></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base(layout.BaseProps{
			Title:     "エクスポート",
			Role:      role,
			CSRFToken: middleware.CSRFTokenFrom(ctx),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
